// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebvpmdcjwpgtjuooxhrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVidnBtZGNqd3BndGp1b294aHJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMjk5MzEsImV4cCI6MjA2NzYwNTkzMX0.DDcFUe5E6nlmIMkeUn37nmcBTdEz9ShHkN5bshcWEeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});